/**
 * Git-derived publish/modified dates for the static SEO landers.
 * Source of truth: scripts/seo-page-dates.json, generated by
 * scripts/generate-seo-page-dates.mjs (re-run after meaningful content edits).
 * Feeds Article JSON-LD (datePublished/dateModified) and visible
 * "Updated <date>" bylines. Falls back to a fixed baseline (site launch era)
 * for routes missing from the manifest — never `new Date()`, so the freshness
 * signal stays honest and build-stable.
 */
import manifest from "../../../scripts/seo-page-dates.json";

type PageDates = { published: string; modified: string };

const FALLBACK: PageDates = { published: "2026-03-21", modified: "2026-03-21" };

const dates = manifest as Record<string, PageDates>;

/** Look up dates for a route path ("/pm-interview-prep") or bare slug. */
export function pageDates(slugOrPath: string): PageDates {
  const path = slugOrPath.startsWith("/") ? slugOrPath : `/${slugOrPath}`;
  return dates[path] ?? FALLBACK;
}

/** "2026-07-03" → "July 3, 2026" for visible bylines. */
export function formatPageDate(isoDate: string): string {
  const [y, m, d] = isoDate.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}
